GdC-Framework/GdC_lib

- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnGroupVehicle.sqf
Fix issues
https://github.com/GdC-Framework/GdC_lib/issues/2
https://github.com/GdC-Framework/GdC_lib/issues/3
> Fix default parameters, waypoint for formation

- gdc_lib_main/config.cpp
- gdc_lib_main/functions/util/fn_inventoryBriefing.sqf
> Amelioration de inventoryBriefing

- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnGroupVehicle.sqf
Signed-off-by: Mystery <mysteryjuju42@gmail.com>
> Fix Lucy Spawn Vehicle function for vehicles with commander slot

- gdc_lib_main/functions/util/fn_inventoryBriefing.sqf
- gdc_lib_main/functions/utilInternal/fn_StringStartWith.sqf
StartWith => tested
InventoryBriefing => tested
> Fix StartWith method and improve inventoryBriefing

- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnStaticInf.sqf
Signed-off-by: Mystery <mysteryjuju42@gmail.com>
> Improve lucySpawnStaticInf to return spawned units

- gdc_lib_main/config.cpp
- gdc_lib_main/functions/gdc_choppa/fn_choppa.sqf
- gdc_lib_main/functions/gdc_choppa/fn_choppaCall.sqf
- gdc_lib_main/functions/gdc_extra/fn_extraCall.sqf
- gdc_lib_main/functions/gdc_extra/fn_extraCancel.sqf
- gdc_lib_main/functions/utilInternal/fn_animVehicleDoor.sqf
- choppa : l'hélico n'éteint plus ses moteurs immédiatement lorsqu'il se pose.
- Amélioration de la supression des WP
>  Améliorations pour gdc_extra et gdc_choppa

- gdc_lib_main/functions/gdc_halo/fn_halo.sqf
- gdc_lib_main/functions/gdc_halo/fn_haloPos.sqf
- gdc_lib_main/functions/gdc_halo/fn_haloServer.sqf
- Ouverture de la porte pour plus d'aéronefs
- Allumage de la lumière en cabine pour plus d'aéronefs
- Pas d'ajout de marqueurs en cas de DZ prédéfinie
- Extinction des feux de position de l'aéronef
- Améliorations du code
> Améliorations pour gdc_halo

- gdc_lib_main/functions/gdc_halo/fn_halo.sqf
- gdc_lib_main/functions/gdc_halo/fn_haloPlayer.sqf
- gdc_lib_main/functions/gdc_halo/fn_haloPos.sqf
- gdc_lib_main/functions/gdc_halo/fn_haloServer.sqf
- spawn de l'avion en agl au lieu de asl
- vérification qu'il y a assez de places pour tout le monde dans l'avion
> Corrections pour gdc_halo

- gdc_lib_main/config.cpp
- gdc_lib_main/functions/util/fn_createGroupCompo.sqf
Une fonction qui crée une composition de groupe à partir de probabilités.
> Ajout createGroupCompo

- gdc_lib_main/functions/gdc_pluto/fn_plutoDoArty.sqf
- gdc_lib_main/functions/gdc_pluto/fn_plutoDoQRF.sqf
- gdc_lib_main/functions/gdc_pluto/fn_plutoSAD.sqf
- Meilleur tri des cibles pour QRF et ARTY 
- Pas de WP QRF sur l'eau
> Corrections pour gdc_pluto

- gdc_lib_main/functions/gdc_lucy/fn_lucyInit.sqf
Signed-off-by: Mystery <mysteryjuju42@gmail.com>
> Change cleaning of dead bodies timing from 600 to 3600

- gdc_lib_main/functions/gdc_halo/fn_halo.sqf
- gdc_lib_main/functions/gdc_halo/fn_haloServer.sqf
Paramètre pour le side de l'avion
> Améliorations gdc_halo

- gdc_lib_main/functions/gdc_mission_making/fn_initGdcConfig.sqf
Je pense que ceci devrait faire l'affaire.
> Rendre initGdcConfig respawn compatible

- gdc_lib_main/functions/gdc_gaia/control/orders/fn_doTransport.sqf
- gdc_lib_main/functions/gdc_gaia/control/orders/fn_doTransportAttack.sqf
Les véhicules NON gaia était réquisitionné afin de déplacer les groupes GAIA
Je dis non !
> Gaia fix transport

- gdc_lib_main/functions/gdc_lucy/index.hpp
- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyReinforcement.sqf
- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyTransportReinforcement.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnGroupInfParadrop.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnGroupVehicle.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnVehicle.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnVehicleCrew.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnVehicleReinforcement.sqf
Ce rework pourra contenir :
- Nouvelle fonction de spawn de véhicule
- Possible nouvelle fonction de renfort infanterie
- Possible rework des fonctions de renforts (pour fonctionner avec la nouvelle fonction de spawn des véhicules)
> Rework Lucy

- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyTransportReinforcement.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnGroupInfParadrop.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnStaticInf.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnVehicle.sqf
- gdc_lib_main/functions/gdc_mission_making/fn_initGdcConfig.sqf
- gdc_lib_main/functions/gdc_pluto/fn_pluto.sqf
- fix pour lucyTransportReinforcement
- Ajout getidr dans lucySpawnStaticInf
- lucyTransportReinforcement : Vitesse par défaut réduite
- PLUTO : suppression de la ligne qui empêchait l'exécution en multi hosté
- PLUTO : Fix pour le HC
> Hotfix 1.9.6

- gdc_lib_main/config.cpp
- gdc_lib_main/functions/gdc_mission_making/fn_3denExportMultipleClasses.sqf
- gdc_lib_main/functions/gdc_mission_making/fn_3denExportMultiplePos.sqf
- gdc_lib_main/functions/gdc_mission_making/fn_3denFillMedicalBackpack.sqf
- gdc_lib_main/functions/gdc_mission_making/index.hpp
- 3denExportMultiplePos
- 3denExportMultipleClasses
- 3denFillMedicalBackpack
> Ajout d'outils dans 3DEN

- gdc_lib_main/functions/utilInternal/fn_hasRadio.sqf
- gdc_lib_main/functions/utilInternal/fn_hasRadioOnRightChannel.sqf
- gdc_lib_main/functions/utilInternal/index.hpp
> Add hasRadio without check on channel + improve method to not check all items

- gdc_lib_main/functions/util/fn_addSingleUseAction.sqf
- gdc_lib_main/functions/util/fn_addSingleUseHoldAction.sqf
- gdc_lib_main/functions/util/index.hpp
- gdc_lib_main/functions/utilInternal/fn_expressionToString.sqf
- gdc_lib_main/functions/utilInternal/fn_getUniqueId.sqf
- gdc_lib_main/functions/utilInternal/index.hpp
Testé uniquement en local via les scripts suivant.
Donc utilisant uniquement le passage d'expression et non des fichiers.
GDC_fnc_addSingleUseAction
`
[a2, ["Hey2!", { systemChat "heuuu2"; }]] call GDC_fnc_addSingleUseAction;
`
GDC_fnc_addSingleUseHoldAction
```
[ 
a1,            
"Hack Laptop2",           
"\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_connect_ca.paa",  
"\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_connect_ca.paa",  
"_this distance _target < 3",       
"_caller distance _target < 3",       
{},              
{},              
{ systemChat "Yeah"; },     
{},              
[],              
6,              
0,              
true,             
false             
] call GDC_fnc_addSingleUseHoldAction;
```
> Add single use action

- gdc_lib_main/functions/util/fn_waitUntilPlayerInMarker.sqf
- gdc_lib_main/functions/util/index.hpp
- gdc_lib_main/functions/utilInternal/fn_hasRadio.sqf
If #67 is not accepted, I make a mistake in my commits ^^ so have to remove revert the first commit before.
> Add utils for scripted trigger

- gdc_lib_main/functions/utilInternal/fn_hasRadio.sqf
The function exists from ACRE, so... use it :)
http://acre.idi-systems.com/api/api_general.html#acre_api_fnc_hasKindOfRadio
> Review hasRadion functions

- gdc_lib_main/functions/gdc_lucy/fn_lucyInit.sqf
- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyAddWaypointListMoveCycle.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnStaticInf.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnVehicle.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnVehicleCrew.sqf
- Autoriser une position pour le 2e paramètre de fn_lucyinit
> Modifs diverses de LUCY

- gdc_lib_main/functions/gdc_choppa/fn_choppa.sqf
- gdc_lib_main/functions/gdc_extra/fn_extra.sqf
- gdc_lib_main/functions/gdc_gaia/fn_internalInit.sqf
- gdc_lib_main/functions/gdc_halo/fn_halo.sqf
- gdc_lib_main/functions/gdc_lucy/fn_lucyInit.sqf
- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyAddWaypoint.sqf
- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyAddWaypointListMoveCycle.sqf
- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyGroupRandomPatrol.sqf
- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyGroupRandomPatrolFixPoints.sqf
- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyReinforcement.sqf
- gdc_lib_main/functions/gdc_lucy/moves/fn_lucyTransportReinforcement.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnGroupInf.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnGroupInfParadrop.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnGroupVehicle.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnStaticInf.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnVehicle.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnVehicleCrew.sqf
- gdc_lib_main/functions/gdc_lucy/spawn/fn_lucySpawnVehicleReinforcement.sqf
- gdc_lib_main/functions/util/fn_addSingleUseAction.sqf
- gdc_lib_main/functions/util/fn_addSingleUseHoldAction.sqf
- gdc_lib_main/functions/util/fn_chooseIAHelicoInsert.sqf
- gdc_lib_main/functions/util/fn_chooseSpawnPos.sqf
- gdc_lib_main/functions/util/fn_createGroupCompo.sqf
- gdc_lib_main/functions/util/fn_rosterBriefing.sqf
- gdc_lib_main/functions/util/fn_waitUntilPlayerInMarker.sqf
- gdc_lib_main/functions/utilInternal/fn_hasRadio.sqf
- gdc_lib_main/functions/utilInternal/fn_hasRadioOnRightChannel.sqf
- gdc_lib_main/functions/utilInternal/fn_prepareBlacklistForRandomPos.sqf
Pour éviter d'avoir des erreurs au milieu de la fonction, mais bien sur le mauvais paramètre dont il est réèlement question :)
Idéalement, il faudrait utiliser PARAM plutôt que PARAM**S** 
Actuellement l'erreur renvoie sur le début du PARAMS, en spécifiant qu'on attendait TEL type, et qu'on a reçu tel type... mais on ne sait pas de quel paramètre il est question :)
> Secure parameters

- gdc_lib_main/config.cpp
- gdc_lib_main/functions/gdc_mission_making/fn_3denCreateEndTrigger.sqf
- gdc_lib_main/functions/gdc_mission_making/fn_3denExportMultipleClasses.sqf
- gdc_lib_main/functions/gdc_mission_making/fn_3denExportMultiplePos.sqf
- gdc_lib_main/functions/gdc_mission_making/index.hpp
- Ajout 3denCreateEndTrigger
- 3denExportMultiplePos : support des positions uniques
- 3denExportMultiplePos : nouveau mode AGL [x,y,0]
> Améliorations outils 3DEN :

- gdc_lib_main/functions/gdc_mission_making/fn_initGdcConfig.sqf
> nouveau ace medical phase 2

- gdc_lib_main/functions/util/fn_chooseSpawnPos.sqf
- gdc_lib_main/functions/utilInternal/fn_secureStringArrayToArray.sqf
- gdc_lib_main/functions/utilInternal/index.hpp
resolve #83 
Add a whitelist parameter in function chooseSpawnPos
NOT TESTED YET
> chooseSpawnPos => whitelist spawn positions

- gdc_lib_Unit_Tests.Altis/init.sqf
- gdc_lib_Unit_Tests.Altis/mission.sqm
- gdc_lib_Unit_Tests.Altis/util/init.sqf
- gdc_lib_Unit_Tests.Altis/util/tests.sqf
- gdc_lib_main/functions/util/fn_chooseSpawnPos.sqf
- gdc_lib_main/functions/util/fn_chooseSpawnPos_onMapSingleClick.sqf
- gdc_lib_main/functions/util/index.hpp
> Choose spawn pos whitelist

- gdc_lib_main/functions/util/fn_posToGrid.sqf
- gdc_lib_main/functions/util/index.hpp
Ajout de la fonction **posToGrid**, permet de récupérer les coordonnées de grilles avec un nombre x de chiffres voulu. Quelques tests effectués, je vous laisse la triturer dans tous les sens pour trouver de possibles problèmes.
> Xdigits grid coords

- gdc_marker_filter/functions/fn_filterMarker.sqf
- gdc_marker_filter/ui/gdc_ctrlMrkFilter.hpp
- Reprise du positionnement des contrôles pour tenir compte des différentes UI scales
- Correction d'un bug quand aucun marqueur d'un certain type n'existait sur la map
> Correction gdc_marker_filter

- gdc_lib_main/functions/gdc_lucy/fn_lucyInit.sqf
> Fix drowing bug at spawn

- gdc_lib_main/functions/util/fn_getInventoryBriefing.sqf
- gdc_lib_main/functions/util/fn_inventoryBriefing.sqf
- gdc_lib_main/functions/util/fn_inventoryBriefing_v2.sqf
- Added tooltips for pictures
- Some texts were transfered to picture tooltips
- Added player ranks in the list
> Updated InventoryBriefing

- gdc_lib_main/functions/gdc_pluto/fn_pluto.sqf
- gdc_lib_main/functions/gdc_pluto/fn_plutoAction.sqf
- gdc_lib_main/functions/gdc_pluto/fn_plutoAnalize.sqf
- gdc_lib_main/functions/gdc_pluto/fn_plutoDoArty.sqf
- gdc_lib_main/functions/gdc_pluto/fn_plutoDoQRF.sqf
first argument can now be an array of sides.
> Pluto now accept mulitple sides

- gdc_lib_main/functions/gdc_pluto/fn_pluto.sqf
- gdc_lib_main/functions/gdc_pluto/fn_plutoHearing.sqf
- gdc_lib_main/functions/gdc_pluto/index.hpp
J'ai trouvé des cotons tiges pour nettoyer les oreilles des ia.
> Pluto hearing

- gdc_lib_main/functions/gdc_zeushicom/fn_createhicommodule.sqf
- gdc_lib_main/functions/gdc_zeushicom/fn_zeushicom.sqf
curator cam area moves with player
> HICOM update 02 23
